Static anomaly detection for pr
rehanvdm/serverless-website-analytics pull request #89
Opened 2024-05-05 17:37 UTC by kc0bfv

This does not directly address issue #75, but does address some comments there.

This PR adds a minimumViews parameter which must be exceeded before the anomaly detection considers a set of views to be an anomaly.  The default is 0, so by default this is off.  An example is provided in the anomaly detection documentation.

2024-05-06 03:38 UTC, rehanvdm requested changes
Looks good, just a few small changes

2024-05-06 03:38 UTC, rehanvdm commented on docs/ANOMALY_DETECTION.md
> +- `MINIMUM_VIEWS` This is a minimum value, below which any other values will not be considered to be breaching the threshold.  It defaults to 0.  As an example - if you have a spike from 1 view over
```suggestion
- `MINIMUM_VIEWS` The minimum number of views before an evaluation is considered breached. Continuing with the example above, if the `Minimum Views` parameter is specified as 101, which is less than the actual view of 100, then the predicted value, breaching multiplier, and the breaching threshold are irrelevant as the evaluation will not be able to transition into the breaching state.
```

2024-05-06 03:38 UTC, rehanvdm commented on infra/src/index.ts
> +   * The minimum threshold views before allowing breaching.
```suggestion
   * The minimum number of views before an evaluation is considered breached.
```

2024-05-06 03:41 UTC, rehanvdm commented
I ran the `'Simulate and predict'` test in `tests/application/backend/cron-anomaly-detection/index.ts` with: 

Value at 0: 
![image](https://github.com/rehanvdm/serverless-website-analytics/assets/22810856/5b295e30-fbb4-4d50-8093-ab4e33793caa)

Value at 30:
![image](https://github.com/rehanvdm/serverless-website-analytics/assets/22810856/6fec9e32-521d-4c73-bc67-8d3382bf3551)

It does a good job of filtering out those small spikes that should not be considered anomalies, thanks!

2024-05-26 21:19 UTC, kc0bfv commented
Updated!  Sorry that took so long - vacation, work, blah blah.  Actually I didn't realize GitHub made it so easy to commit recommendations like that!

2024-06-02 12:52 UTC, rehanvdm approved these changes

2024-06-02 12:53 UTC, rehanvdm commented
No problem, I know how it goes and this is open source, so no obligation. Thanks again.

2024-06-02 12:53 UTC, merged